# Generated by Django 5.1.6 on 2025-02-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_category_slug_property_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(max_length=400, verbose_name='Açıklama'),
        ),
    ]
