# Generated by Django 5.1.6 on 2025-02-10 18:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_alter_property_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='floor',
            field=models.IntegerField(default=django.utils.timezone.now, verbose_name='Kat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='is_featured'),
        ),
    ]
