# Generated by Django 5.1.6 on 2025-02-10 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_property_floor_alter_property_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='floor',
        ),
    ]
