# Generated by Django 5.1.6 on 2025-02-10 18:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_remove_property_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='floor',
            field=models.IntegerField(default=django.utils.timezone.now, verbose_name='Kat'),
            preserve_default=False,
        ),
    ]
