# Generated by Django 5.1.6 on 2025-02-10 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0006_property_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='floor',
        ),
    ]
