# Generated by Django 5.1.6 on 2025-02-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0007_remove_property_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='floor',
            field=models.IntegerField(default=1, verbose_name='Kat'),
        ),
    ]
