# Generated by Django 5.1.6 on 2025-02-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0008_property_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='description_en',
            field=models.TextField(max_length=400, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='property',
            name='description_tr',
            field=models.TextField(max_length=400, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='property',
            name='description_uk',
            field=models.TextField(max_length=400, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='property',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='property',
            name='title_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='property',
            name='title_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Başlık'),
        ),
    ]
