# Generated by Django 5.1.6 on 2025-02-14 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0009_property_description_en_property_description_tr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='property',
            name='description_tr',
        ),
        migrations.RemoveField(
            model_name='property',
            name='description_uk',
        ),
        migrations.RemoveField(
            model_name='property',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='property',
            name='title_tr',
        ),
        migrations.RemoveField(
            model_name='property',
            name='title_uk',
        ),
    ]
