# Generated by Django 5.1.6 on 2025-02-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0010_remove_property_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(max_length=400, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
    ]
