# Generated by Django 5.1.6 on 2025-02-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0013_alter_property_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('flaw', 'Flaw')], default='draft', max_length=10),
        ),
    ]
