# Generated by Django 5.1.6 on 2025-02-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0014_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='available',
            field=models.BooleanField(default=False, verbose_name='Mevcut'),
        ),
    ]
