# Generated by Django 5.1.6 on 2025-06-05 19:47

import realestate.custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0015_alter_property_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='photo',
            field=models.ImageField(storage=realestate.custom_storages.ImageSettingStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_1',
            field=models.ImageField(blank=True, storage=realestate.custom_storages.ImageSettingStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_2',
            field=models.ImageField(blank=True, storage=realestate.custom_storages.ImageSettingStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_3',
            field=models.ImageField(blank=True, storage=realestate.custom_storages.ImageSettingStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_4',
            field=models.ImageField(blank=True, storage=realestate.custom_storages.ImageSettingStorage(), upload_to=''),
        ),
    ]
